### ISSUE TITLE
Dead links to api.mongodb.org in the documentation

### ISSUE THREAD

**Issue by stusmall** [appsignal/mongo-rust-driver#22]
This crate's documentation often links out to mongodb's C driver docs.  It looks like at some point these links broke.  One example is http://api.mongodb.org/c/current/mongoc_query_flags_t.html has should be http://mongoc.org/libmongoc/current/mongoc_query_flags_t.html

**Comment by thijsc** [comment]
Fixed in 87effd5dc27cae1a50fda94aa06cb154714da18e
