### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by thedrow** [appsignal/mongo-rust-driver#41]
Given that async/await is finally landing, maybe we can provide async/await support for this library?

**Comment by thijsc** [comment]
Async support would be awesome. But, the C driver itself does not currently offer an async interface.

It would be possible to have a layer that runs some threads that poll the C driver and convert these to async behaviour. I'm not eager to do anything like that in this crate. I'd like this to be an as-minimal as possible but still safe and usable.

If I'm missing anything and there would indeed be a good way to connect a sync driver to the async ecosystem I'd love to learn about it.

**Comment by thedrow** [comment]
I didn't know that the C driver does not offer an async interface. It's weird since it does for Java and Python so I imagined there is an async interface for C.
I think that maybe a separate crate could be created for wrapping MongoDB operations in a way that will allow it to run in a [futures::executor::ThreadPool](https://docs.rs/futures/0.2.1/futures/executor/struct.ThreadPool.html).
Is that something that you are willing to do? Or is it a massive undertaking?

**Comment by thijsc** [comment]
I'm not against having support for. I'd say it should probably be behind a feature flag so we only pull in the futures dependency when necessary.

Honestly I'm not going to write this myself. This is not something we would use at my company. So on the one hand it's not something that would derive a lot of value for me. On the other hand I wouldn't use it and would't be in a good position to make it awesome.

If you'd like to take a stab at it I'd definitively offer any assistance and advice I can.

**Comment by thijsc** [comment]
For a bit more context, a lot of the behaviour of this crate is sort of async already.

We do a lot of insertions with this driver using https://docs.rs/mongo_driver/0.12.1/mongo_driver/collection/struct.BulkOperation.html. If you use that you can have the server process your updates in a batch. Also just using the iterator the C driver will do a lot of stuff in the background to make delivering results fast.

**Comment by thijsc** [comment]
@thedrow are you interested in taking a stab at this? A first step could be to try out the integration with a thread pool a bit and post some code examples here. If you're not interested in pursuing this I will close the issue.

**Comment by thedrow** [comment]
Let's close this for now.
