### ISSUE TITLE
Trying to pass between threads

### ISSUE THREAD

**Issue by goriunov** [appsignal/mongo-rust-driver#49]
When i am trying to clone pool and pass it to another thread i am getting this error:
```
*mut mongoc_sys::bindings::mongoc_client_t` cannot be sent between threads safely
```

what would you suggest to properly pass pool to another thread ?

**Comment by thijsc** [comment]
What are you trying to do here? Do you have code illustrating the issue?

**Comment by inv2004** [comment]
@goriunov I suppose Arc::new(pool) would be the easiest solution here.

**Comment by gngeorgiev** [comment]
@goriunov You should get a new client in each new thread from the `ClientPool` by using `pop`. The `ClientPool` is what you should be sharing between threads. http://mongoc.org/libmongoc/1.12.0/mongoc_client_pool_t.html
